default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fundcollection_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: fundcollection_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: fundcollection_production
  username: fundcollection
  password: <%= ENV["FUNDCOLLECTION_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
